[supervisord]
nodaemon=true
user=frappe

[program:web]
directory=/home/frappe/frappe-bench
command=/usr/local/bin/gunicorn -w ${GUNICORN_WORKERS:-2} -t 120 -b 0.0.0.0:%(ENV_PORT)s frappe.app:application
autostart=true
autorestart=true
stopsignal=QUIT
stopasgroup=true
killasgroup=true
priority=10

[program:worker-default]
directory=/home/frappe/frappe-bench
command=/usr/local/bin/bench worker --queue default
autostart=true
autorestart=true
priority=20

[program:worker-short]
directory=/home/frappe/frappe-bench
command=/usr/local/bin/bench worker --queue short
autostart=true
autorestart=true
priority=20

[program:worker-long]
directory=/home/frappe/frappe-bench
command=/usr/local/bin/bench worker --queue long
autostart=true
autorestart=true
priority=20

[program:scheduler]
directory=/home/frappe/frappe-bench
command=/usr/local/bin/bench schedule
autostart=true
autorestart=true
priority=30
